---
apiVersion: v1
kind: Service
metadata:
  name: react-app-srv
  namespace: suu
spec:
  type: LoadBalancer
  selector:
    app: react-flux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
