apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-flux
  namespace: suu
  labels:
    app: react-flux
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-flux
  template:
    metadata:
      labels:
        app: react-flux
    spec:
      containers:
        - name: react-flux
          image: bkulawska/flux-19:1685053131
          ports:
            - containerPort: 3000
