name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bkulawska/flux-19:$(date +%s)
  modify-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Modify file
        run: |
          sed -i 's|image: bkulawska/flux-19:.*|image: bkulawska/flux-19:$(date +%s)|' kubernetes/react-deployment.yaml
      - name: Commit changes
        run: |
          git config --global user.email "kulawska1507@gmail.com"
          git config --global user.name "bkulawska"
          git commit -a -m "Update docker image"
          git push
